# syntax=docker/dockerfile:1
FROM python:3.9-alpine
WORKDIR /code
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5557
EXPOSE 5558
EXPOSE 5559
EXPOSE 5560
EXPOSE 5561
EXPOSE 6666
EXPOSE 7777
EXPOSE 9000
CMD python -u rest-server.py