version: "3.9"
services:
  node1:
    environment:
      - name=node1
    build: .

  node2:
    environment:
      - name=node2
    build: .

  node3:
    environment:
      - name=node3
    build: .

  node4:
    environment:
      - name=node4
    build: .

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "9000:9000"