# syntax=docker/dockerfile:1
FROM python:3.8-bullseye
WORKDIR /code
#RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . .
EXPOSE 9000
CMD python -u rest-server.py